erDiagram
  surahs ||--o{ ayahs : "has"
  ayahs ||--o{ words : "has"
  surahs ||--o{ lessons : "has"
  surahs ||--o{ bookmarks : "has"
  ayahs ||--o{ bookmarks : "has"

  surahs {
  }

  ayahs {
  }

  words {
  }

  lessons {
  }

  bookmarks {
  }
